### ISSUE TITLE
503 Service Unavailable?

### ISSUE THREAD

**Issue by JustinGrote** [dotps1/HPWarranty#28]
Hey, great module, but when trying to use it I'm getting nothing but 503 service errors at the client registration step for HPE. Is this just me or is it down?

**Comment by beanska** [comment]
I'm seeing it as well. Perhaps we circle back at a later date and see if it is still an issue.

**Comment by dotps1** [comment]
again!  i swear HP is trying to screw us!  lol.

**Comment by kaiweiz** [comment]
may i ask do you guys know if the service itself is back up? I wrote something last summer similar in a different language that stopped working since the HP HPE split. 

I am revisiting it, but if the whole service is not available, I won't bother fixing my code...

**Comment by dotps1** [comment]
It seems to be working for me.  But one thing i want to say is that last week i set up CI, so that when the AppVeyor build is successful it will publish to the PowerShell gallery.  Well, i noticed today, that the psd1 was totally jacked.  So when i did `ipmo HPWarranty` none of the cmdlets where exporting.

i fixed that and just pushed a new build (currently qued at the time of this writing: https://ci.appveyor.com/project/dotps1/hpwarranty), so you may want to grab the new version from the gallery 2.5.8 is the latest.

thanks.
