### ISSUE TITLE
SCCM AmbiguousParameterSet

### ISSUE THREAD

**Issue by b-zylka** [dotps1/HPWarranty#30]
Unable to pull warranty information from SCCM.  WMI is properly inventoried and populated in the database.  It looks as the ComputerName is pulling the system name instead of the computer hostname.

:error:

Get-HPIncWarrantyEntitlement : Parameter set cannot be resolved using the specified named parameters.
At line:1 char:96
+ ... Database 'CM_MCV' -IntergratedSecurity | Get-HPIncWarrantyEntitlement
+                                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (@{ComputerName=...esk 800 G1 SFF}:PSObject) [Get-HPIncWarrantyEntitlem
   ent], ParameterBindingException
    + FullyQualifiedErrorId : AmbiguousParameterSet,Get-HPIncWarrantyEntitlement

**Comment by dotps1** [comment]
The `-ComputerName` Parameter is the computer where the SCCM Database is being hosted.

**Comment by b-zylka** [comment]
No, that would be the `-SqlServer` parameter correct?  Otherwise you would be entering the same data twice.  If I leave the `-ComputerName` parameter off the command, it pulls results from the DB for all computers with the same error.  I can substitute "comp123" for the name of any computer and get the same result as long as it's an HP.  Removing the pipe the computer information is displayed from the SCCM database no problem.  Something isn't passing into the piped command.

Here's an example of the command issued:
`Get-HPSystemInformationFromCMDB -SqlServer 'sccmdb' -Database 'CM_MCV' -IntegratedSecurity -ComputerName 'comp123' | Get-HPIncWarrantyEntitlement`

**Comment by dotps1** [comment]
LOL, sorry, you are right, I haven't really used this function much as I don't have SCCM in my current job.  I'm not sure why it would not work, because this is all it does with the ComputerName in the query:
```
AND Computer_System_DATA.Name00 LIKE '%$($ComputerName[$i])%'
```

the [$i] is because the ComputerName is a [String[]] so you should be able to do `-ComputerName Comp1, Comp2`

You could try removing all that foreach out of there.  I don't have a CCM environment to test with at the moment.

**Comment by dotps1** [comment]
oh, nvm, its how its being piped into the Get-HPIncWarrantyEntitlement cmdlet, try doing this:
```powershell
Get-HPSystemInformationFromCMDB -SqlServer 'sccmdb' -Database 'CM_MCV' -IntegratedSecurity -ComputerName 'comp123' | %{ Get-HPIncWarrantyEntitlement -SerialNumber $_.SerialNumber -ProductNumber $_.ProductNumber }
```
its something with the parameter binding.  I think its because its trying to bind the ComputerName and the SerialNumber,ProductNumber all at the same time, which are part of different ParameterSets.

**Comment by b-zylka** [comment]
That did the trick, but did have to use `-IntergratedSecurity` instead of `-IntegratedSecurity` for spelling :).

**Comment by dotps1** [comment]
LOL, cannot believe no one has cought that one!  i will look at the parameter binding when i get some time, because you should not have to do that foreach.  I think if i just change the Property Name from ComputerName to Name in the object that gets returned from SCCM, that should work.  because i still want the pipeline support for ComputerName in the cmdlet so you can do:
```PowerShell
Get-ADComputer | Get-HPIncWarrantyEntitlement
```
thanks.

**Comment by b-zylka** [comment]
Awesome.  Feature request for myself would be in the formating so that I can do a ` out-gridview` and have the columns separated out.

**Comment by dotps1** [comment]
this should take care of it:  https://www.powershellgallery.com/packages/HPWarranty/2.6.1
